# Generated by Django 3.1.2 on 2020-10-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='middle_initial',
        ),
        migrations.AddField(
            model_name='emailuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Middle Initial'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
