# Generated by Django 3.1.2 on 2020-11-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
