# Generated by Django 3.1.2 on 2020-10-27 10:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('representatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfractionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('points', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('wfh_days_forfeit', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='WFH Days Forfeit')),
                ('rolling_months', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(36)])),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='representatives.representative')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='infractions.infractiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
