# Generated by Django 3.1.2 on 2020-10-20 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Initial')),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Work E-mail Address')),
                ('type', models.CharField(blank=True, choices=[('AGENT', 'Agent'), ('IPR', 'IPR')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], max_length=50)),
                ('last_status_date', models.DateField(verbose_name='Status Date')),
                ('last_hire_date', models.DateField()),
                ('division', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('workgroup', models.CharField(max_length=150, verbose_name='Work Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
